Vagrant.configure("2") do |config|
	config.vm.define "centos7" do |node|
		# 设置虚拟机的Box
		node.vm.box = "centos/7"

		# 设置虚拟机的主机名
		node.vm.hostname="centos7"

		# 设置虚拟机的IP，根据VirtualBox Host-Only Network配置
		node.vm.network "private_network", ip: "192.168.56.100", netmask: "255.255.255.0"

		# 设置主机与虚拟机的共享目录
		# node.vm.synced_folder "~/Documents/vagrant/share", "/home/vagrant/share"

		# VirtaulBox相关配置
		node.vm.provider "virtualbox" do |v|
			# 设置虚拟机的名称
			v.name = "centos7"
			# 设置虚拟机的内存大小
			v.memory = 4096
			# 设置虚拟机的CPU个数
			v.cpus = 4
		end
	end
end